workflows:
  android-apk:
    name: TradeSphere Android APK
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Set Flutter SDK path
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk