import 'package:flutter/material.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import '../../services/api_client.dart';
import '../../services/payment_api.dart';
import '../payments/payment_status_screen.dart';

class WalletScreen extends StatefulWidget { const WalletScreen({super.key}); @override State<WalletScreen> createState()=>_WalletScreenState(); }
class _WalletScreenState extends State<WalletScreen> {
  late Razorpay _razorpay; String? _paymentIntentId; String? _orderId; bool _busy=false;
  @override void initState(){super.initState();_razorpay=Razorpay();_razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS,_onSuccess);_razorpay.on(Razorpay.EVENT_PAYMENT_ERROR,_onError);_razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET,_onExternalWallet);}
  @override void dispose(){_razorpay.clear();super.dispose();}
  Future<void> _startDeposit() async { final c=TextEditingController(); final amount=await showDialog<double>(context:context,builder:(_)=>AlertDialog(title:const Text('Add money'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount (INR)',prefixText:'₹ ')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,double.tryParse(c.text)),child:const Text('Pay'))])); if(amount==null||amount<1||!mounted)return; setState(()=>_busy=true); try{final o=await PaymentApi().createRazorpayDeposit(amount);_paymentIntentId=o.paymentIntentId;_orderId=o.orderId;_razorpay.open({'key':o.keyId,'amount':o.amountPaise,'currency':o.currency,'name':'TradeSphere','description':'Wallet deposit','order_id':o.orderId,'method':{'upi':true,'card':true,'netbanking':true,'wallet':true},'theme':{'color':'#2563FF'}});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>_busy=false);}}
  Future<void> _onSuccess(PaymentSuccessResponse r) async { try { if(_orderId==null||_paymentIntentId==null)return; await PaymentApi().verifyRazorpayPayment(orderId:_orderId!,paymentId:r.paymentId??'',signature:r.signature??''); final intent=await PaymentApi().getIntent(_paymentIntentId!); if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>PaymentStatusScreen(intent:intent))); }catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Payment received, but server verification is pending: $e')));} }
  void _onError(PaymentFailureResponse r){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Payment failed: ${r.message??'Unknown error'}')));}
  void _onExternalWallet(ExternalWalletResponse r){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('External wallet selected: ${r.walletName??'UPI wallet'}')));}
  @override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('Wallet',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:18),const Card(child:ListTile(leading:Icon(Icons.account_balance_wallet),title:Text('Available balance'),subtitle:Text('Server ledger balance'),trailing:Text('Live'))),const SizedBox(height:18),FilledButton.icon(onPressed:_busy?null:_startDeposit,icon:const Icon(Icons.add_card),label:Text(_busy?'Opening payment...':'Add money with UPI / Google Pay')),const SizedBox(height:12),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('Payments stay pending until TradeSphere verifies the Razorpay response and webhook. Google Pay appears through the Razorpay UPI checkout when available on the device.'))),]));
}
