import 'package:flutter/material.dart';
import '../../services/auth_api.dart';
import '../../services/api_client.dart';

class SignupScreen extends StatefulWidget { const SignupScreen({super.key}); @override State<SignupScreen> createState()=>_SignupScreenState(); }
class _SignupScreenState extends State<SignupScreen>{ final name=TextEditingController(),email=TextEditingController(),password=TextEditingController(),confirm=TextEditingController(); bool loading=false;
 @override void dispose(){name.dispose();email.dispose();password.dispose();confirm.dispose();super.dispose();}
 Future<void> signup() async {if(name.text.trim().isEmpty||email.text.trim().isEmpty||password.text.length<8||password.text!=confirm.text){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Check your details. Password must be 8+ characters and match.')));return;}setState(()=>loading=true);try{await AuthApi().signup(name.text.trim(),email.text.trim(),password.text);if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e is ApiException?e.message:e.toString())));}finally{if(mounted)setState(()=>loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Create account')),body:ListView(padding:const EdgeInsets.all(22),children:[const SizedBox(height:20),const Text('Join TradeSphere',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),const SizedBox(height:24),TextField(controller:name,decoration:const InputDecoration(labelText:'Full name')),const SizedBox(height:14),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:14),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password (8+ characters)')),const SizedBox(height:14),TextField(controller:confirm,obscureText:true,decoration:const InputDecoration(labelText:'Confirm password')),const SizedBox(height:22),FilledButton(onPressed:loading?null:signup,child:Text(loading?'Creating...':'Create account'))])); }
